version: '2.1'

services:
  playground:
    build: ./
    command: npm run playground
    volumes:
      - ./src/:/usr/src/app/src:ro
      - ./playground:/usr/src/app/playground:ro
    expose:
      - '8989'
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
